language: ruby
rvm:
  - 2.4.2 # make sure this matches our VMs
cache: bundler
services:
  - postgresql
before_script:
  - bundle exec rake travis_setup_postgres

bundler_args: --without 'production development deploy'

notifications:
  email: false
